In [4]:
data_file = "/media/stormfield/Data/resources/lastfm/userid-timestamp-artid-artname-traid-traname.tsv"

In [5]:
import pandas as pd

In [7]:
raw_df = pd.read_csv(data_file,
                     low_memory=False, 
                     sep='\t', names=['user_id','timestamp','artist_id','artist', 'track_id','track'],
                     parse_dates=['timestamp'])

since it took a while to read. lets quickly check the memory and see of there are any improvemnts we can make

## Data exploration

First lets gets some information regarding the dtypes and memeory involed

In [10]:
raw_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19098862 entries, 0 to 19098861
Data columns (total 6 columns):
user_id      object
timestamp    datetime64[ns, UTC]
artist_id    object
artist       object
track_id     object
track        object
dtypes: datetime64[ns, UTC](1), object(5)
memory usage: 7.1 GB

Since we are time bound, we will optimize for memory if required later. For now this can be easily handled by most morden machines.

lets take a look at how the data looks like.

In [15]:
raw_df.sample(5)

,user_id,timestamp,artist_id,artist,track_id,track
13330652,user_000704,2007-06-06 00:25:51+00:00,172e1f1a-504d-4488-b053-6344ba63e6d0,Nick Cave & The Bad Seeds,b41dcee8-716b-4e24-b34e-2d603e30b4a3,Deanna
5349985,user_000274,2007-10-11 20:02:14+00:00,f4c967a4-7591-4bba-8237-82e171a2fa7f,X-Ray Spex,1c6df6d6-d89e-44ed-9dca-0bb5d7260760,Oh Bondage Up Yours!
16655117,user_000861,2007-03-07 12:02:51+00:00,2865730a-5757-4005-875e-84d6274cb1c0,Revolting Cocks,10267304-f269-41a8-a2c5-a026f0a69bed,You Often Forget (Malignant)
18288441,user_000950,2007-04-07 17:31:29+00:00,NaN,Consul The Educated Monkey,NaN,Poema De La Tormenta
14013489,user_000743,2007-12-20 21:47:07+00:00,006f0783-c5a0-458b-a9da-f8551f7ebe77,Richard Hawley,4f45ddfd-53d5-471c-83e2-4d976b818211,The Sun Refused To Shine

### Statistics of each column
<a id='staticstics_cell'></a>

In [20]:
raw_df.describe()

,user_id,timestamp,artist_id,artist,track_id,track
count,19098862,19098862,18498009,19098862,16936136,19098850
unique,992,17454739,107295,173923,960402,1083480
top,user_000949,2009-02-26 21:29:15+00:00,a74b1b7f-71a5-4011-9441-d0b5e4122711,Radiohead,db16d0b3-b8ce-4aa8-a11a-e4d53cc7f8a6,Intro
freq,183103,248,115099,115099,3991,17561
first,NaN,2005-02-14 00:00:07+00:00,NaN,NaN,NaN,NaN
last,NaN,2013-09-29 18:32:04+00:00,NaN,NaN,NaN,NaN

#### 1. Check for nulls

In [21]:
raw_df.isnull().sum()

user_id            0
timestamp          0
artist_id     600853
artist             0
track_id     2162726
track             12
dtype: int64

In [23]:
raw_df[raw_df['artist_id'].isnull()].head()

,user_id,timestamp,artist_id,artist,track_id,track
50,user_000001,2009-05-02 14:30:56+00:00,NaN,Rocket Empire,NaN,Simmer Down Jammie
78,user_000001,2009-05-01 11:58:15+00:00,NaN,Rocket Empire,NaN,Simmer Down Jammie
87,user_000001,2009-05-01 09:36:10+00:00,NaN,Rocket Empire,NaN,Simmer Down Jammie
92,user_000001,2009-05-01 09:12:21+00:00,NaN,Nicken,NaN,Lifeb
95,user_000001,2009-05-01 08:58:19+00:00,NaN,Ivan Enot,NaN,Grooves Of The Heart

As we can see above the artist_id & track_id have lot of nulls. Since the corresponding artist/track columns aren't null its best to drop those 'id' columns and proceed

In [24]:
df = raw_df.drop(columns=['artist_id', 'track_id'])

Thats much cleaner isn't it ? (PFB)

In [26]:
df[df['artist'] == 'Rocket Empire'].head()

         user_id                 timestamp         artist               track
50   user_000001 2009-05-02 14:30:56+00:00  Rocket Empire  Simmer Down Jammie
78   user_000001 2009-05-01 11:58:15+00:00  Rocket Empire  Simmer Down Jammie
87   user_000001 2009-05-01 09:36:10+00:00  Rocket Empire  Simmer Down Jammie
102  user_000001 2009-05-01 08:18:35+00:00  Rocket Empire  Simmer Down Jammie
117  user_000001 2009-05-01 05:59:11+00:00  Rocket Empire  Simmer Down Jammie

### 2. Combine columns to get unique workable data

When we pulled [staticstics](#staticstics_cell), we observerd that there is a lot of 'intro' tracks. This shouldn't be a suprising. To get unique track details we need to combine the artist & track columns

Based on [Last Fm](https://www.last.fm/tag/sampling) and general consensus we can combine both columns using an aceeptable format, ie `Artist_name - Track_name`

In [28]:
df['song'] = df['artist'] + ' - ' + df['track']

lets see if the data came correct

In [31]:
df.sample(5)

,user_id,timestamp,artist,track,song
11742312,user_000628,2006-08-16 14:34:33+00:00,Talking Heads,Heaven (Live),Talking Heads - Heaven (Live)
17502363,user_000909,2007-03-14 04:50:23+00:00,Radiohead,Just,Radiohead - Just
7770403,user_000412,2007-03-14 16:14:28+00:00,Tunng,Sweet William,Tunng - Sweet William
4406585,user_000229,2007-06-22 08:40:06+00:00,Metallica,Phantom Lord,Metallica - Phantom Lord
9223762,user_000496,2006-06-10 19:26:20+00:00,Pantera,Throes Of Rejection,Pantera - Throes Of Rejection

We ca drop the artist & track columns for now, since we will use the song colums for further analysis

In [35]:
df.drop(columns=['artist', 'track'],inplace=True)

Lets sample the data one last time

In [37]:
df.sample(5)

,user_id,timestamp,song
2329584,user_000119,2007-03-08 17:14:57+00:00,Black Label Society - Give Yourself To Me
15904910,user_000824,2008-05-08 18:18:55+00:00,Reuben - Freddy Kreuger
16790440,user_000869,2008-04-26 10:06:06+00:00,Nightmares On Wax - Damn
12324500,user_000667,2006-07-05 12:38:51+00:00,Cheap Trick - I Want You To Want Me (Live)
156029,user_000006,2006-10-08 20:58:46+00:00,Metallica - Turn The Page

### Part A


Create a list of user IDs, along with the number of distinct songs each user has played

In [83]:
distinct_songs_by_user = df.groupby('user_id')['song'].nunique().reset_index()

In [102]:
# quick rename of the result column
distinct_songs_by_user.rename(columns={'song':'count'},inplace=True)

In [104]:
distinct_songs_by_user.head()

       user_id  count
0  user_000001   3143
1  user_000002   8537
2  user_000003   4682
3  user_000004   6210
4  user_000005   2014

 **quick verfication**

quick sanity check reveals that user_000982 occurs 54 times. Yes I did manually go through the 55 entries as well to see if they are unique. But just incase lets try verifying it another way

In [100]:
distinct_songs_by_user[distinct_songs_by_user['user_id']=='user_000982']

         user_id  count
974  user_000982     54

In [101]:
df[df['user_id']=='user_000982'].nunique()

user_id       1
timestamp    55
song         54
dtype: int64

**print results**

In [112]:
with pd.option_context('display.max_rows', -1):
    print(distinct_songs_by_user)

..           ...    ...
         user_id  count
0    user_000001   3143
1    user_000002   8537
2    user_000003   4682
3    user_000004   6210
4    user_000005   2014
5    user_000006   7982
6    user_000007   1122
7    user_000008    619
8    user_000009   2624
9    user_000010    991
10   user_000011   7840
11   user_000012  13048
12   user_000013   3141
13   user_000014    282
14   user_000015   2166
15   user_000016   7531
16   user_000017  12742
17   user_000018   1143
18   user_000019   3353
19   user_000020   2032
20   user_000021  10105
21   user_000022   5866
22   user_000023   2090
23   user_000024  10579
24   user_000025  12052
25   user_000026   4423
26   user_000027    844
27   user_000028   6725
28   user_000029   9169
29   user_000030   3811
30   user_000031  19864
31   user_000032   1467
32   user_000033   7273
33   user_000034   5314
34   user_000035   4392
35   user_000036   2298
36   user_000037   2690
37   user_000038   3785
38   user_000039   1675
39   user_000040   4196
40   user_000041   7470
41   user_000042   1013
42   user_000043   6889
43   user_000044   2130
44   user_000045    358
45   user_000046   2038
46   user_000047   2027
47   user_000048    535
48   user_000049    333
49   user_000050   4384
50   user_000051   2358
51   user_000052   8973
52   user_000053  10480
53   user_000054   5313
54   user_000055   1440
55   user_000056   5868
56   user_000057    421
57   user_000058   1583
58   user_000059   6518
59   user_000060  13150
60   user_000061      9
61   user_000062   4282
62   user_000063   2405
63   user_000064   5411
64   user_000065   2844
65   user_000066    666
66   user_000067   7277
67   user_000068  16226
68   user_000069   3624
69   user_000070   2544
70   user_000071   1021
71   user_000072   4583
72   user_000073   2051
73   user_000074  16116
74   user_000075   5064
75   user_000076   4400
76   user_000077    403
77   user_000078   4567
78   user_000079   4938
79   user_000080    577
80   user_000081    585
81   user_000082   3228
82   user_000083   4606
83   user_000084   2110
84   user_000085   2521
85   user_000086   5424
86   user_000087   3014
87   user_000088    198
88   user_000089   9086
89   user_000090   1879
90   user_000091   8784
91   user_000092   2894
92   user_000093   4322
93   user_000094   4352
94   user_000095   9430
95   user_000096   6433
96   user_000097  16530
97   user_000098    254
98   user_000099    377
99   user_000100   1867
100  user_000101    116
101  user_000102   5402
102  user_000103   3468
103  user_000104   4899
104  user_000105   2589
105  user_000106    434
106  user_000107  11612
107  user_000108  12153
108  user_000109   2653
109  user_000110   3907
110  user_000111   2184
111  user_000112  12772
112  user_000113   2133
113  user_000114   4138
114  user_000115   1691
115  user_000116   7899
116  user_000117   3252
117  user_000118    813
118  user_000119   2872
119  user_000120   6769
120  user_000121   3705
121  user_000122   2416
122  user_000123   3467
123  user_000124   1380
124  user_000125   3339
125  user_000126    885
126  user_000127   1820
127  user_000128   1076
128  user_000129   6513
129  user_000130   2713
130  user_000131   9439
131  user_000132   5925
132  user_000133   4662
133  user_000134   9243
134  user_000135  18767
135  user_000136   1714
136  user_000137   4073
137  user_000138   1533
138  user_000139   1868
139  user_000140    197
140  user_000141   3360
141  user_000142   5866
142  user_000143    309
143  user_000144    680
144  user_000145   2619
145  user_000146    169
146  user_000147   7696
147  user_000148   2558
148  user_000149  15403
149  user_000150    706
150  user_000151   3936
151  user_000152   4496
152  user_000153   2228
153  user_000154   4188
154  user_000155   5916
155  user_000156   6948
156  user_000157    232
157  user_000158   1920
158  user_000159   9740
159  user_000160   7867
160  user_000161   8108
161  user_000162  22143
162  user_000163   1860
163  user_000164    842
164  user_000165   2816
165  user_000166   1291
166  user_000167   6631
167  user_000168   2267
168  user_000169   2924
169  user_000170   7626
170  user_000171    433
171  user_000172   2745
172  user_000173    837
173  user_000174  18156
174  user_000175    814
175  user_000176    538
176  user_000177   3200
177  user_000178  12432
178  user_000179   2469
179  user_000180   5145
180  user_000181   2609
181  user_000182   9843
182  user_000183    184
183  user_000184    290
184  user_000185   4210
185  user_000186    904
186  user_000187   3521
187  user_000188   9540
188  user_000189   4815
189  user_000190   8353
190  user_000191   7115
191  user_000192    545
192  user_000193    887
193  user_000194   3315
194  user_000195   1338
195  user_000196   1812
196  user_000197    981
197  user_000198   1625
198  user_000199  16599
199  user_000200    748
200  user_000201   1066
201  user_000202   1313
202  user_000203   5686
203  user_000204    421
204  user_000205   3901
205  user_000206   7640
206  user_000207    754
207  user_000208   3227
208  user_000209   4219
209  user_000210  19269
210  user_000211   6346
211  user_000212    801
212  user_000213   3498
213  user_000214   2005
214  user_000215   7999
215  user_000216   1626
216  user_000217   1017
217  user_000218   5797
218  user_000219   7342
219  user_000220   2537
220  user_000221   1523
221  user_000222   7526
222  user_000223   6924
223  user_000224   3809
224  user_000225    497
225  user_000226   7946
226  user_000227   3788
227  user_000228    282
228  user_000229   6263
229  user_000230   1526
230  user_000231     41
231  user_000232    459
232  user_000233  16381
233  user_000234   1999
234  user_000235   6507
235  user_000236   2799
236  user_000237   8682
237  user_000238   2416
238  user_000239   4192
239  user_000240      3
240  user_000241   3938
241  user_000242   7239
242  user_000243   1287
243  user_000244   2418
244  user_000245   2436
245  user_000246   2437
246  user_000247    194
247  user_000248     50
248  user_000249  16327
249  user_000250   6558
250  user_000251   3967
251  user_000252   3357
252  user_000253   1234
253  user_000254   2581
254  user_000255   5417
255  user_000256   4723
256  user_000257    549
257  user_000258   1255
258  user_000259   4582
259  user_000260   3230
260  user_000261   2898
261  user_000262   5099
262  user_000263   2096
263  user_000264   3615
264  user_000265    751
265  user_000266   8407
266  user_000267   6870
267  user_000268   5257
268  user_000269   6716
269  user_000270   1847
270  user_000271   4954
271  user_000272    100
272  user_000273   5163
273  user_000274  13179
274  user_000275    840
275  user_000276   4061
276  user_000277   1840
277  user_000278   3468
278  user_000279   4743
279  user_000280   8471
280  user_000281   9166
281  user_000282    192
282  user_000284   8064
283  user_000285   4605
284  user_000286    112
285  user_000288   1281
286  user_000289    994
287  user_000290  11249
288  user_000291   1236
289  user_000292    592
290  user_000293  13669
291  user_000294   6509
292  user_000295   2204
293  user_000296   6333
294  user_000297   1098
295  user_000298   9112
296  user_000299   1741
297  user_000300   2576
298  user_000301     92
299  user_000302   1165
300  user_000303   6597
301  user_000304   8945
302  user_000305    726
303  user_000306   7834
304  user_000307    686
305  user_000308     69
306  user_000309   3083
307  user_000310   1383
308  user_000311    594
309  user_000312   5187
310  user_000313  20355
311  user_000314   1145
312  user_000315    968
313  user_000316   1898
314  user_000317  12528
315  user_000318   2202
316  user_000319   6294
317  user_000320   6790
318  user_000321    409
319  user_000322  12242
320  user_000323   6400
321  user_000324   2422
322  user_000325   4363
323  user_000326   5751
324  user_000327    724
325  user_000328    518
326  user_000329   6158
327  user_000330   1656
328  user_000331   1914
329  user_000332      2
330  user_000333    460
331  user_000334   1338
332  user_000335    192
333  user_000336    243
334  user_000337   6522
335  user_000338   4967
336  user_000339   2522
337  user_000340   6024
338  user_000341  12195
339  user_000342   1000
340  user_000343   3186
341  user_000344  10807
342  user_000345  26055
343  user_000346   4031
344  user_000347   5679
345  user_000348  11877
346  user_000349  11288
347  user_000350   2511
348  user_000351   5421
349  user_000352    187
350  user_000353   1182
351  user_000354   6741
352  user_000355   1524
353  user_000356   5810
354  user_000357  15846
355  user_000358   3993
356  user_000359  15028
357  user_000360   4208
358  user_000361   3540
359  user_000362   7074
360  user_000363   4580
361  user_000364    152
362  user_000366   9551
363  user_000367    699
364  user_000368    541
365  user_000369    693
366  user_000370  12687
367  user_000371   7727
368  user_000372   4789
369  user_000373   3387
370  user_000374   3124
371  user_000375    327
372  user_000376  13458
373  user_000377   3036
374  user_000378   1603
375  user_000379   2977
376  user_000380   4215
377  user_000381   9924
378  user_000382  10816
379  user_000383   3850
380  user_000384  15454
381  user_000385   1859
382  user_000386     86
383  user_000387   5374
384  user_000388   6386
385  user_000389   4016
386  user_000390    908
387  user_000391   4815
388  user_000392   1017
389  user_000393   1472
390  user_000394   6901
391  user_000395    570
392  user_000396   3250
393  user_000397   9907
394  user_000398   7506
395  user_000399    221
396  user_000400   3641
397  user_000401   2823
398  user_000402    259
399  user_000403   3103
400  user_000404   1232
401  user_000405   1421
402  user_000406    448
403  user_000407   6742
404  user_000408    417
405  user_000409  12666
406  user_000410    398
407  user_000411    900
408  user_000412  12955
409  user_000413   1182
410  user_000414   1207
411  user_000415   9856
412  user_000416    485
413  user_000417   1444
414  user_000418    841
415  user_000419    284
416  user_000420   2376
417  user_000421   1049
418  user_000422   2466
419  user_000423   5183
420  user_000424   2004
421  user_000425   8480
422  user_000426   6148
423  user_000427  35934
424  user_000429  10559
425  user_000430   4973
426  user_000431  10091
427  user_000432   3385
428  user_000433   2091
429  user_000434   2865
430  user_000435    374
431  user_000436   4030
432  user_000437   6617
433  user_000438   1915
434  user_000439   7261
435  user_000440   3804
436  user_000441   1953
437  user_000442   4771
438  user_000443   1717
439  user_000444   2415
440  user_000445   3718
441  user_000446   4094
442  user_000447    879
443  user_000448    513
444  user_000449    852
445  user_000450   3454
446  user_000451  23513
447  user_000452   2391
448  user_000453   6330
449  user_000454   1329
450  user_000455     85
451  user_000456   1854
452  user_000457    798
453  user_000458   8590
454  user_000459   1577
455  user_000460    943
456  user_000461   7708
457  user_000462   2017
458  user_000463   2265
459  user_000464   2494
460  user_000465   1440
461  user_000467   9653
462  user_000468   4479
463  user_000469   4728
464  user_000471  12880
465  user_000472   1884
466  user_000473    393
467  user_000474   2668
468  user_000475   3102
469  user_000476   2153
470  user_000477   9512
471  user_000478   2557
472  user_000479   7398
473  user_000480   5392
474  user_000481   1244
475  user_000482   3821
476  user_000483  19479
477  user_000484   4241
478  user_000485    804
479  user_000486   2248
480  user_000487    502
481  user_000488    941
482  user_000489   1549
483  user_000490   1964
484  user_000491   3858
485  user_000492     53
486  user_000493   4884
487  user_000494   1437
488  user_000495   2150
489  user_000496   5612
490  user_000497   1010
491  user_000498   1071
492  user_000499   9323
493  user_000500   6560
494  user_000501   5485
495  user_000502   4480
496  user_000503   6655
497  user_000504   3081
498  user_000505   3368
499  user_000506   1276
500  user_000507   4904
501  user_000508   2512
502  user_000509  13253
503  user_000510   2002
504  user_000511   2400
505  user_000512   6054
506  user_000513   3858
507  user_000514   4410
508  user_000515  12577
509  user_000516   2829
510  user_000517   3200
511  user_000518   2958
512  user_000519    209
513  user_000520   2322
514  user_000521   1098
515  user_000522   6523
516  user_000523   4337
517  user_000524   2249
518  user_000525   2014
519  user_000526    360
520  user_000527    722
521  user_000528   1606
522  user_000529  14769
523  user_000530    855
524  user_000531   2239
525  user_000532   4453
526  user_000533     28
527  user_000534   3904
528  user_000535   6675
529  user_000536  10670
530  user_000537   3593
531  user_000538     16
532  user_000539   1368
533  user_000540   4448
534  user_000541    211
535  user_000542   3527
536  user_000543   9315
537  user_000544  18459
538  user_000545   1063
539  user_000546   3790
540  user_000547    269
541  user_000548    170
542  user_000549   2241
543  user_000550   4869
544  user_000551    761
545  user_000552   2773
546  user_000553   6414
547  user_000554   5369
548  user_000555    875
549  user_000556    333
550  user_000557   3016
551  user_000558   3896
552  user_000559    830
553  user_000560    249
554  user_000561     76
555  user_000562   1181
556  user_000563     70
557  user_000564   8927
558  user_000565  12642
559  user_000566      6
560  user_000567    470
561  user_000568   4124
562  user_000569   7654
563  user_000570   9635
564  user_000571  13721
565  user_000572   6042
566  user_000573   3135
567  user_000574   2141
568  user_000575   3454
569  user_000576   3391
570  user_000577  18227
571  user_000578   2485
572  user_000579   6354
573  user_000580   2212
574  user_000581   6493
575  user_000582   1353
576  user_000583   1607
577  user_000584   4972
578  user_000585   4574
579  user_000586    899
580  user_000587   2090
581  user_000588   4499
582  user_000589   2387
583  user_000590   1955
584  user_000591   2211
585  user_000592   1281
586  user_000593   7303
587  user_000594   4912
588  user_000595   5649
589  user_000596   4616
590  user_000597    149
591  user_000598    723
592  user_000599   4597
593  user_000600   5468
594  user_000601   1467
595  user_000602   1160
596  user_000603   6185
597  user_000604   8058
598  user_000605    920
599  user_000606   3715
600  user_000607   1872
601  user_000608     76
602  user_000609   6318
603  user_000610   7114
604  user_000611  16547
605  user_000612   4442
606  user_000613    904
607  user_000614   2979
608  user_000615   5774
609  user_000616   3914
610  user_000617  11499
611  user_000618     51
612  user_000619   2775
613  user_000620   4495
614  user_000621   1274
615  user_000622    704
616  user_000623   2022
617  user_000624   1234
618  user_000625   4016
619  user_000626    603
620  user_000627   7753
621  user_000628   2722
622  user_000629   6306
623  user_000630  11171
624  user_000631    784
625  user_000632   6629
626  user_000633   3588
627  user_000634   3763
628  user_000635   5471
629  user_000636   2456
630  user_000637   2615
631  user_000638    237
632  user_000639   6113
633  user_000640    857
634  user_000641   9553
635  user_000642    871
636  user_000643   2164
637  user_000644   2552
638  user_000645   1464
639  user_000646   1008
640  user_000647   8801
641  user_000648   3419
642  user_000649   1492
643  user_000650   5003
644  user_000651   4503
645  user_000652   4733
646  user_000653   2599
647  user_000654   3190
648  user_000655   9113
649  user_000656   4905
650  user_000657    342
651  user_000658   2199
652  user_000659   6271
653  user_000660   1272
654  user_000661   8365
655  user_000662   3429
656  user_000664    495
657  user_000665   2548
658  user_000666   5691
659  user_000667   1990
660  user_000668   1291
661  user_000669   3644
662  user_000670   7085
663  user_000671   3482
664  user_000672   1714
665  user_000673   1471
666  user_000674    358
667  user_000675  12576
668  user_000676   1184
669  user_000677     62
670  user_000678   4426
671  user_000679    858
672  user_000680  10218
673  user_000681  43241
674  user_000682   1376
675  user_000683   1127
676  user_000684  14263
677  user_000685  13229
678  user_000686      5
679  user_000687   5996
680  user_000688   2720
681  user_000689  14903
682  user_000690  11422
683  user_000691  63001
684  user_000692  22392
685  user_000693   1220
686  user_000694   5251
687  user_000695   5861
688  user_000696    890
689  user_000697   2803
690  user_000698   1630
691  user_000699   4047
692  user_000700   5229
693  user_000701   2439
694  user_000702  31276
695  user_000703  13876
696  user_000704   3006
697  user_000705   7266
698  user_000706   4164
699  user_000707   2488
700  user_000708   4743
701  user_000709  12559
702  user_000710   1655
703  user_000711   1654
704  user_000712   3577
705  user_000713   1387
706  user_000714   3075
707  user_000715   2270
708  user_000716   2060
709  user_000717   3056
710  user_000718   5558
711  user_000719   1963
712  user_000720   1548
713  user_000721   4011
714  user_000722  11123
715  user_000723    147
716  user_000724   1388
717  user_000725   1964
718  user_000726   2167
719  user_000727   8861
720  user_000728   5996
721  user_000729   4223
722  user_000730  10601
723  user_000731   1353
724  user_000732   3521
725  user_000733   7536
726  user_000734   1874
727  user_000735   4234
728  user_000736    280
729  user_000737   2909
730  user_000738    991
731  user_000739   1760
732  user_000740   5452
733  user_000741   1892
734  user_000742   1207
735  user_000743   9945
736  user_000744   4195
737  user_000745   6413
738  user_000746   1518
739  user_000747   5603
740  user_000748    774
741  user_000749   2459
742  user_000750  14374
743  user_000751  17327
744  user_000752   2597
745  user_000753   8500
746  user_000754   1992
747  user_000755   7924
748  user_000756   4016
749  user_000757   1435
750  user_000758   2851
751  user_000759     81
752  user_000760   1942
753  user_000761   9260
754  user_000762   3251
755  user_000763   3408
756  user_000764   1448
757  user_000765   3001
758  user_000766   5901
759  user_000767  10025
760  user_000768   1852
761  user_000769    946
762  user_000770   7823
763  user_000771   4516
764  user_000772   3292
765  user_000773   3705
766  user_000774  34620
767  user_000775   1846
768  user_000776   2714
769  user_000777    494
770  user_000778    533
771  user_000779   8170
772  user_000780   7173
773  user_000781   5179
774  user_000782   4722
775  user_000783  24569
776  user_000784    385
777  user_000785     75
778  user_000786    542
779  user_000787   3602
780  user_000788   6370
781  user_000789  11272
782  user_000790   7346
783  user_000791  15417
784  user_000792  19164
785  user_000793  10880
786  user_000794   5743
787  user_000795   2522
788  user_000796    366
789  user_000797    745
790  user_000798   7104
791  user_000799   1413
792  user_000800  39542
793  user_000801   2761
794  user_000802   5912
795  user_000803   3784
796  user_000804   8603
797  user_000805    378
798  user_000806   2659
799  user_000807  14151
800  user_000808   1490
801  user_000809   7539
802  user_000810   5445
803  user_000811   1100
804  user_000812    882
805  user_000813   1058
806  user_000814   5117
807  user_000815     12
808  user_000816   2948
809  user_000817    691
810  user_000818   2339
811  user_000819   8165
812  user_000820   4719
813  user_000821   1878
814  user_000822   2778
815  user_000823   5446
816  user_000824   4585
817  user_000825   3787
818  user_000826   3956
819  user_000827   1911
820  user_000828   4100
821  user_000829   5711
822  user_000830  10125
823  user_000831   2523
824  user_000832   3839
825  user_000833   5173
826  user_000834   1620
827  user_000835   5732
828  user_000836   6761
829  user_000837  12713
830  user_000838   3956